name: nuxeo
version: 0.3.0.3
github: apeyroux/nuxeo
author: Alexandre Peyroux
maintainer: alex@px.io
category: System
license: BSD3
description: Nuxeo tools

library:
  # buildable: false
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - aeson
    - attoparsec
    - base >= 4.2 && < 5
    - bytestring
    - conduit
    - conduit-extra
    - http-conduit
    - http-types
    - text
    - time
    - url

executable:
  # buildable: false
  main: Main.hs
  source-dirs: app
  ghc-options: -Wall -threaded -rtsopts
  dependencies:
    - base >= 4.2 && < 5
    - nuxeo
    - optparse-applicative
    - text
