name: nuxeo
version: 0.2.0.3
github: https://github.com/apeyroux/nuxeo
author: Alexandre Peyroux
maintainer: alex@xn--wxa.email

ghc-options: -Wall

library:
  source-dirs: src
dependencies:
  - base
  - attoparsec
  - bytestring
  - conduit
  - conduit-extra
  - text
  - time
